# Generated by Django 2.2.8 on 2019-12-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inscrito',
            fields=[
                ('id', models.AutoField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('nombres', models.CharField(max_length=70)),
                ('apellidos', models.CharField(max_length=70)),
                ('dni', models.IntegerField(unique=True)),
                ('e_mail', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.IntegerField(blank=True)),
                ('direccion', models.CharField(max_length=150, null=True)),
                ('observacion', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('asesora', models.CharField(max_length=50, null=True)),
                ('fecha_matricula', models.DateField(null=True)),
                ('fecha_diploma', models.DateField(null=True)),
                ('observacion', models.TextField(blank=True, max_length=2000, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Curso')),
                ('inscrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Inscrito')),
            ],
        ),
        migrations.CreateModel(
            name='Ugel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ugel', models.CharField(max_length=100, unique=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('observacion', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'ordering': ['ugel'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mod_entregado', models.CharField(max_length=50)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.Matricula')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='ugel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.Ugel'),
        ),
    ]
