# Generated by Django 2.2.8 on 2019-12-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20191211_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='descripcion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
